### PR TITLE
Update to newest cfltk and fix build

### PR DESCRIPTION
**Pull request by mgord9518**
As it was, zfltk would refuse to build due to a couple errors and undefined symbols

### CODE REVIEW

**Comment by MoAlyousef** [comment]
Thank you 🙏

**Comment by mgord9518** [comment]
@MoAlyousef is there any way to build it without installing cfltk to your system? I experienced some issues building inside an Ubuntu container that has some immutable parts of the root filesystem.

I found the original build (where build.zig automatically downloaded and compiled cfltk) a lot easier to use

**Comment by MoAlyousef** [comment]
Currently no. But I can revert to the original build.

**Comment by mgord9518** [comment]
@MoAlyousef Thanks! It's working great now

**Pull request merged**
